shop/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\admin\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin_panel', 'middleware' => ['auth']], function () {
    Route::get('/', 'App\Http\Controllers\admin\DashboardController@dashboard')->name('admin.index');
    Route::resource('category', \App\Http\Controllers\admin\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\admin\PostController::class);
    Route::resource('orders', \App\Http\Controllers\admin\OrdersController::class);

});
Route::get('/send', [\App\Http\Controllers\CheckoutController::class, 'mail']);
Route::group(['prefix' => 'category'], function () {
    Route::get('/', [\App\Http\Controllers\PostController::class, 'show']);
    Route::get('{type}', [\App\Http\Controllers\PostController::class, 'show']);
});

Route::group(['prefix' => 'product'], function () {
    Route::get('{id}', [\App\Http\Controllers\PostController::class, 'one_product']);
});
Route::get('/cart', [\App\Http\Controllers\CartController::class, 'GetFromCart'])->name('cart');
Route::post('/add-to-cart', [\App\Http\Controllers\CartController::class, 'addToCart'])->name('add-to-cart');
Route::get('/checkout', [\App\Http\Controllers\CheckoutController::class, 'index'])->name('checkout');
Route::post('/checkout', [\App\Http\Controllers\CheckoutController::class, 'add_order'])->name('add.order');


Route::name('user.')->group(function () {
    Route::view('/private', 'private')->middleware('auth')->name('private');


    Route::get('/login', function () {
        if (Auth::check()) {
            \Illuminate\Support\Facades\Session::flash('flash message', 'Вы уже вошли');
            return redirect(route('user.private'));

        }
        return view('login');
    })->name('login');
    Route::post('/login', [\App\Http\Controllers\loginController::class, 'login']);


    Route::get('logout', function () {
        Auth::logout();
        Session::flash('flash_message', 'Вы успешно вышли');
        return redirect('/');
    })->name('logout');


    Route::get('/registration', function () {
        if (Auth::check()) {
            return redirect(route('user.login'));
        }
        return view('registration');
    })->name('registration');
    Route::post('/registration', [\App\Http\Controllers\LoginController::class, 'save']);

});

Route::get('/', function () {
    return view('index');
});

Route::get('/contact', function () {
    return view('contact');
});

shop/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Category;

class Post extends Model
{
    use HasFactory;
    protected $fillable=[
        'title',
        'cost',
        'text',
        'cat_id',
        'available',
        'img'
        ];


    public function category(){
        return $this->belongsTo('App\Models\Category','cat_id');
    }

    public function validateRules()
    {
        return [
            'title'=>'required',
            'cost'=>'required',
            'text'=>'required',
            'cat_id'=>'required',
            'available'=>'required'
        ];
    }
}

shop/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Models\Category;

class PostController extends Controller
{

    public function show(Post $post, Category $category,$type=null)
    {
        if($type){
            $posts=$post->where('cat_id',$type)->orderBy('created_at','DESC')->get();
        }
        else{
            $posts=Post::orderBy('created_at','DESC')->get();
        }
        $categories=Category::orderBy('created_at','DESC')->get();
        return view('category',[
            'posts'=>$posts,
            'categories'=>$categories
        ]);
    }

    //получение отдельного продукта
    public function one_product(Post $post,$id){
        $posts=$post->where('id',$id)->get();
        return view('product',[
            'post'=>$posts,
        ]);
    }


}

shop/app/Http/Controllers/admin/PostController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Models\Category;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts=Post::orderBy('created_at','DESC')->get();
        return view('admin.post.index',[
            'posts'=>$posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::orderBy('created_at','desc')->get();
        return view('admin.post.create',[
            'categories'=>$categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Post $model)
    {
        $validator = Validator::make(
            $request->all(),
            $model->validateRules() );

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator->errors()
                ); }

        $post= new Post();
        $post->fill($request->all());
        $post->save();

        return redirect()->back()->withSuccess('Товар успешно добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $posts=Post::orderBy('created_at','DESC')->get();
        return view('category',[
            'posts'=>$posts
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->back()->withSuccess('Категория была успешно удалена');
    }
}

shop/resources/views/admin/post/create.blade.php
@extends('layouts.admin_layout')

@section('title', 'Добавить статью')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить сатью</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">

                        <!-- form start -->
                        <form action="{{ route('post.store') }}" method="POST">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Название</label>
                                    <input type="text" name="title" class="form-control" id="exampleInputEmail1"
                                           placeholder="Введите название товара" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">цена</label>
                                    <div class="row">
                                    <input type="" name="cost" class="form-control" id="exampleInputEmail1" style="width: 200px; text-align:right"
                                           placeholder="цена" required><h3 class="wobble">$</h3>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="checkbox" id="avail" name="available" value="1">
                                    <label for="avail">наличие</label>
                                </div>
                                <div class="form-group">
                                    <!-- select -->
                                    <div class="form-group">
                                        <label>Выберите категорию</label>
                                        <select name="cat_id" class="form-control" required>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category['id'] }}">{{ $category['title'] }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <textarea name="text" class="editor"></textarea>

                                </div>

                                <div class="form-group">
                                    <label for="feature_image">Изображение товара</label>
                                    <img src="" alt="" class="img-uploaded" style="display: block; width: 300px">
                                    <input type="text" name="img" class="form-control" id="feature_image"
                                           name="feature_image" value="" readonly>
                                    <a href="" class="popup_selector" data-inputid="feature_image">Выбрать изображение</a>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

shop/resources/views/admin/post/index.blade.php
@extends('layouts.admin_layout')

@section('title', 'Все категории')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Все товары</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th>

                            </th>
                            <th style="width: 5%">
                                ID
                            </th>
                            <th>
                                Название
                            </th>
                            <th>
                                цена
                            </th>
                            <th>
                                категория
                            </th>
                            <th>
                                наличие
                            </th>
                            <th style="width: 30%">
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($posts as $post)
                            <tr>
                                <td>
                                    <img src="/{{ $post['img'] }}" height="50px" width="35px">
                                </td>
                                <td>
                                    {{ $post['id'] }}
                                </td>
                                <td>
                                    {{ $post['title'] }}
                                </td>
                                <td>
                                    {{ $post['cost'] }}
                                </td>
                                <td>
                                    {{ $post->category['title'] }}
                                </td>
                                <td>
                                    {{ $post['available'] }}
                                </td>

                                <td class="project-actions text-right">
                                    <form action="{{ route('post.destroy', $post['id']) }}" method="POST"
                                          style="display: inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash">
                                            </i>
                                            Удалить
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection