shop/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\admin\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin_panel', 'middleware' => ['auth']], function () {
    Route::get('/', 'App\Http\Controllers\admin\DashboardController@dashboard')->name('admin.index');
    Route::resource('category', \App\Http\Controllers\admin\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\admin\PostController::class);
    Route::resource('orders', \App\Http\Controllers\admin\OrdersController::class);

});
Route::get('/send', [\App\Http\Controllers\CheckoutController::class, 'mail']);
Route::group(['prefix' => 'category'], function () {
    Route::get('/', [\App\Http\Controllers\PostController::class, 'show']);
    Route::get('{type}', [\App\Http\Controllers\PostController::class, 'show']);
});

Route::group(['prefix' => 'product'], function () {
    Route::get('{id}', [\App\Http\Controllers\PostController::class, 'one_product']);
});
Route::get('/cart', [\App\Http\Controllers\CartController::class, 'GetFromCart'])->name('cart');
Route::post('/add-to-cart', [\App\Http\Controllers\CartController::class, 'addToCart'])->name('add-to-cart');
Route::get('/checkout', [\App\Http\Controllers\CheckoutController::class, 'index'])->name('checkout');
Route::post('/checkout', [\App\Http\Controllers\CheckoutController::class, 'add_order'])->name('add.order');


Route::name('user.')->group(function () {
    Route::view('/private', 'private')->middleware('auth')->name('private');


    Route::get('/login', function () {
        if (Auth::check()) {
            \Illuminate\Support\Facades\Session::flash('flash message', 'Вы уже вошли');
            return redirect(route('user.private'));

        }
        return view('login');
    })->name('login');
    Route::post('/login', [\App\Http\Controllers\loginController::class, 'login']);


    Route::get('logout', function () {
        Auth::logout();
        Session::flash('flash_message', 'Вы успешно вышли');
        return redirect('/');
    })->name('logout');


    Route::get('/registration', function () {
        if (Auth::check()) {
            return redirect(route('user.login'));
        }
        return view('registration');
    })->name('registration');
    Route::post('/registration', [\App\Http\Controllers\LoginController::class, 'save']);

});

Route::get('/', function () {
    return view('index');
});

Route::get('/contact', function () {
    return view('contact');
});

shop/resources/views/admin/index.blade.php
@extends('layouts.admin_layout')
@section('title','главная')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>150</h3>

                            <p>New Orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>53<sup style="font-size: 20px">%</sup></h3>

                            <p>Bounce Rate</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>44</h3>

                            <p>User Registrations</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>65</h3>

                            <p>Unique Visitors</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

shop/resources/views/admin/orders.blade.php
@extends('layouts.admin_layout')


@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Заказы</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                        <tr>

                            <th >
                                ID
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                user
                            </th>
                            <th>
                                country
                            </th>
                            <th>
                                adress
                            </th>
                            <th>
                                total
                            </th>
                            <th>
                                show products
                            </th>
                            <th>
                                delete order
                            </th>


                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($orders as $order)
                            <tr>
                                <td>
                                    {{ $order['id'] }}
                                </td>
                                <td>
                                    {{ $order['Email'] }}
                                </td>
                                <td>
                                    {{ $order['user_id'] }}
                                </td>
                                <td>
                                    {{ $order['Country'] }}
                                </td>
                                <td>
                                    {{ $order['Adress'] }}
                                </td>
                                <td>
                                    {{ $order['Total'] }}$
                                </td>
                                <td>
                                    <form action="{{ route('orders.show', $order['id']) }}" method="POST"
                                          style="display: inline-block">
                                        @csrf
                                        @method('GET')
                                        <button type="submit" class="btn btn-success">
                                            <i class="fab fa-product-hunt"></i>
                                            </i>
                                            show
                                        </button>
                                    </form>

                                </td>
                                <td>
                                    <form action="{{ route('orders.destroy', $order['id']) }}" method="POST"
                                          style="display: inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm delete-btn">
                                            <i class="fas fa-trash">
                                            </i>
                                            Удалить
                                        </button>
                                    </form>
                                </td>


                            </tr>
                        @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

shop/resources/views/admin/product.blade.php
@extends('layouts.admin_layout')


@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">заказы</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th>

                            </th>

                            <th >
                                Название
                            </th>
                            <th>
                                цена
                            </th>
                            <th>
                                категория
                            </th>
                            <th>
                                количество
                            </th>
                            <th>
                               полная цена
                            </th>

                        </tr>

                        </thead>
                        <tbody>
                        @foreach ($products as $product)
                            <tr>
                                <td>
                                    <img src="/{{ $product->post['img'] }}" height="50px" width="35px">
                                </td>
                                <td>
                                    {{ $product->post['title'] }}
                                </td>
                                <td>
                                    {{ $product->post['cost'] }}$
                                </td>
                                <td>
                                    {{ $product->post->category['title'] }}
                                </td>
                                <td>
                                    {{ $product['quantity'] }}
                                </td><td>
                                    {{ $product['quantity']*$product->post['cost']}}$
                                </td>


                            </tr>
                        @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection